Exercise 1:

Create a NumPy array of integers from 1 to 10

In [2]:
import numpy as np
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


Exercise 2:

Create a 3x3 NumPy array filled with zeros

In [4]:
a=np.zeros([3,3])
print(a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Exercise 3:

Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [10]:
a=np.linspace(0,5,10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Exercise 4:

Create a 5x5 identity matrix using NumPy.

In [18]:
import numpy as np
a=np.eye(5,5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Exercise 5:

Create a 4x4 matrix with random values between 0 and 1

In [38]:
a=np.random.random([4,4])
print(a)



[[0.83580489 0.81154779 0.58930568 0.04362333]
 [0.41359517 0.50709893 0.50539645 0.77381173]
 [0.23478652 0.03645383 0.08953707 0.62267522]
 [0.69350226 0.97385475 0.69811684 0.8388737 ]]


Exercise 6:

Find the shape of a NumPy array.

In [39]:
np.shape(a)

(4, 4)

In [40]:
a.shape

(4, 4)

Exercise 7:

Reshape a 1D NumPy array of 16 elements into a 4x4 matrix

In [42]:
a.reshape([4,4])

array([[0.83580489, 0.81154779, 0.58930568, 0.04362333],
       [0.41359517, 0.50709893, 0.50539645, 0.77381173],
       [0.23478652, 0.03645383, 0.08953707, 0.62267522],
       [0.69350226, 0.97385475, 0.69811684, 0.8388737 ]])

Exercise 8:

Find the data type of the elements in a NumPy array.

In [43]:
a.dtype

dtype('float64')

Exercise 9:

Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [47]:
b=np.arange(1,100)
print(b)
b[b%2==0]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Exercise 10:

Generate a 6x6 matrix of random integers between 10 and 50

In [88]:
c=np.random.randint(10,50,[6,6])
print(c)


[[29 12 40 16 17 26]
 [20 32 30 40 42 15]
 [45 34 38 10 31 13]
 [18 15 10 37 41 14]
 [39 12 28 46 34 18]
 [24 43 30 32 39 33]]


Exercise 11:

Slice a 2D NumPy array to extract a submatrix

In [90]:
import numpy as np
d=c[1:3,]
print(d)

[[20 32 30 40 42 15]
 [45 34 38 10 31 13]]


Exercise 12:

Calculate the sum of all elements in a NumPy array.

In [65]:
e=np.arange(1,10)
f=e.sum
print(f)

<built-in method sum of numpy.ndarray object at 0x7f1f2c18cdb0>


Exercise 13:

Calculate the mean, median, and standard deviation of a NumPy array

In [68]:
a=np.arange(1,10)
x=np.mean(a)
print(x)

5.0


In [70]:
y=np.median(a)
print(y)

5.0


In [72]:
z=np.std(a)
print(z)

2.581988897471611


Exercise 14:

Find the maximum and minimum values in a NumPy array.

In [75]:
a=np.arange(1,10)
v=np.argmax(a)
print(v)

8


In [76]:
g=np.argmin(a)
print(g)

0


Exercise 15:

Create a NumPy array of 20 random integers and find the index of the maximum value

In [86]:
my_int=np.random.randint(20,size=(3,4))
print(my_int)
print(np.argmax(my_int))

[[18  3 17  5]
 [ 6 11 17 15]
 [13 11 18  9]]
0


Exercise 16:¶

Create a NumPy array and reverse its elements.

In [91]:
bb=np.flip(a)
print(bb)

[9 8 7 6 5 4 3 2 1]


Exercise 17:

Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [101]:
aaa=np.random.randint(20,30,[3,3])
bbb=np.random.randint(10,15,[3,3])
#print(aaa)
#print(bbb)
print(np.multiply(aaa,bbb))

[[297 364 322]
 [260 273 377]
 [260 338 260]]


Exercise 18:¶

Create a diagonal matrix from a given 1D array

In [100]:
import numpy as np
a=np.arange(1,10)
np.diag(a)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

Exercise 19:

Perform matrix multiplication on two 2D NumPy arrays

In [6]:
import numpy as np
ccc=np.arange(1,10,[2,2])
ddd=np.arange(2,5,[2,2])
print(np.multiply(ccc,ddd))

TypeError: unsupported operand type(s) for /: 'int' and 'list'

Exercise 20:¶

Flatten a 2D NumPy array into a 1D array.

In [9]:
import numpy as np
ads= np.array([[2,0,0], [1,9,7]])
ggg = ads.flatten()
print(ggg)


[2 0 0 1 9 7]


Exercise 21:

Stack two NumPy arrays vertically.

In [11]:
fff = np.vstack(ads)
print(fff)


[[2 0 0]
 [1 9 7]]


Exercise 22:

Stack two NumPy arrays horizontally

In [13]:

w = np.hstack(ads)
print(w)


[2 0 0 1 9 7]


ercise 23:¶

Split a NumPy array into multiple sub-arrays

In [15]:
p = np.array_split(np.array([1, 2, 3, 4, 5, 6,7,8]), 3)
print(p)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


Exercise 24:

Generate a random NumPy array and round each element to two decimal places.

In [18]:
dtype = [('name', 'S10'), ('age', 'i4'), ('height', 'f4')]
structured_array = np.array([('Alice', 25, 5.5), ('Aline', 30, 5.8)], dtype=dtype)
print(structured_array)


[(b'Alice', 25, 5.5) (b'Aline', 30, 5.8)]


Exercise 25:¶

Find the unique elements of a NumPy array.

In [24]:
vv = np.random.randint(1, 10, (3,3))
u = np.unique(vv)
print(u)


[1 2 3 6 7 8 9]


Exercise 26:

Replace all elements in a NumPy array that are less than a specific value with that value

In [26]:
ss = np.transpose(vv)
print(ss)


[[3 8 7]
 [1 6 9]
 [2 1 8]]


Exercise 27:

Find the cumulative sum of the elements in a NumPy array.

In [27]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
result = np.multiply(arr_1, arr_2)
print(result)


[ 4 10 18]


Exercise 28:¶

Create a NumPy array and find the number of non-zero elements in it

In [28]:
dot_product = np.dot(arr_1, arr_2)
print(dot_product)


32


Exercise 29:¶

Create a NumPy array of random integers and sort it in ascending order

In [31]:
cross_product=np.cross(arr_1,arr_2)
print(cross_product)

[-3  6 -3]


### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [32]:
m = np.array([3, 1, 4, 1, 5, 9])
mm = np.sort(m)
print(mm)


[1 1 3 4 5 9]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1)

In [34]:
sorted_matrix = np.sort(vv, axis=1)
print(sorted_matrix)


[[1 2 3]
 [1 6 8]
 [7 8 9]]


### Exercise 32:
Create two NumPy arrays and find the dot product

In [38]:
dotp = np.cumsum([1,2,3])
print(dotp)


[1 3 6]


### Exercise 33:
Find the trace of a square NumPy matrix

In [44]:
xx = np.cumprod(vv)
print(xx)


[     3      3      6     48    288    288   2016  18144 145152]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector

In [45]:
arr_3 = np.union1d(arr_1, arr_2)
print(arr_3)


[1 2 3 4 5 6]


### Exercise 36:
Find the determinant of a 3x3 matrix

In [46]:
import numpy as np
matrix_2x2 = np.array([[4, 6],
                       [3, 8]])

det_2x2 = np.linalg.det(matrix_2x2)
print("Determinant of the 2x2 matrix is:", det_2x2)




Determinant of the 2x2 matrix is: 14.000000000000004


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix

In [47]:

eigenvalues, eigenvectors = np.linalg.eig(vv)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [13.22481245+0.j          1.88759377+2.34751836j  1.88759377-2.34751836j]
Eigenvectors:
 [[-0.21290902+0.j         -0.01993586+0.3731436j  -0.01993586-0.3731436j ]
 [-0.36140031+0.j          0.46248054-0.46188706j  0.46248054+0.46188706j]
 [-0.90777727+0.j         -0.6581326 +0.j         -0.6581326 -0.j        ]]


### Exercise 38:
Solve a system of linear equations using NumPy

In [48]:

A = np.array([[2, 3],[4, 1]])
B = np.array([5, 6])
solution = np.linalg.solve(A, B)
print(solution)


[1.3 0.8]


### Exercise 39:
Add Gaussian noise to a NumPy array

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements

In [53]:
ddd=np.random.randint(1,10,[4,4])
print(ddd)
print(np.diag(ddd))

[[2 6 6 7]
 [5 4 6 8]
 [5 6 3 5]
 [1 4 2 6]]
[2 4 3 6]
